apiVersion: apps/v1
kind: Deployment
metadata:
  name: ServiceName
  labels:
    app: ServiceName
    deployon: "dsr"
spec:
  replicas: replace_replicas
  selector:
    matchLabels:
      app: ServiceName
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ServiceName
        deployon: "dsr"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ServiceName
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: image_to_be_deployed
        imagePullPolicy: Always
        name: ServiceName
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - |
                apt-get update -y && \
                apt-get install -y curl && \
                curl -LJO "https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v${GCSFUSE_VERSION}/gcsfuse_${GCSFUSE_VERSION}_amd64.deb" && \
                apt-get -y install fuse && \
                apt-get clean && \
                dpkg -i "gcsfuse_${GCSFUSE_VERSION}_amd64.deb" && \
                mkdir -p /edi-outbound-files && gcsfuse --only-dir edi/AS2/outbox ${EDI_SERVER} /edi-outbound-files
          preStop:
            exec:
              command:
              - fusermount
              - -u
              - /edi-outbound-files
        ports:
        - containerPort: 9306
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9306
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9306
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "4"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          # FUSE VERSION - TEMPORARY WORKAROUND
          - name: GCSFUSE_VERSION
            value: 1.2.0        
          # APIGATEWAY URL
          - name: APIGATEWAY_URL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: apigateway.url
          - name: EDICONFIG_URL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: edisplitter.ediConfigUrl
          - name: EDIANALYTICSDATA_URL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: ediAnalyticsDataUrl
          - name: ENV_URL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: replace_logical_env.host.name
          - name: EDI_SERVER
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: replace_logical_env.edi.server.value
          - name: JAEGER_COLLECTOR_URL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: jaeger.collector.url   
          - name: BOOTSTRAP_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: replace_logical_env.kafka.bootstrap.server.url
          - name: EDISPLITTER_INBOUND_KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: replace_logical_env.kafka.topic.inbound
          - name: KAFKA_MAX_REQUEST_SIZE
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: kafka.max.request.size           
          - name: EDISPLITTER_OUTBOUND_KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: replace_logical_env.kafka.topic.outbound 
          - name: KAFKA_SECURITY_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: edisplitter-configmap
                key: kafka.security.protocol
          - name : SSL_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka.broker.certs
                key: keystore.pwd
          - name : SSL_TRUSTSTORE_LOCATION
            value: /etc/certs/kafka/kafka.broker.keystore.jks 
        volumeMounts:
          - mountPath: /etc/certs/kafka
            name: certs
            readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: kafka.broker.certs        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: SvcName
  labels:
    app: ServiceName
    k8s-app: edisplitter
spec:
  selector:
    app: ServiceName
  type: ClusterIP
  ports:
  - port: 9306
    name: web
    targetPort: 9306
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler 
metadata: 
  name: edisplitter
spec: 
  maxReplicas: replace_maxReplicas
  minReplicas: replace_minReplicas
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: hpaSrvName
  metrics: 
  - type: Resource 
    resource: 
      name: cpu
      targetAverageUtilization: 70
