spring:
  application:
    name: edisplitter
  zipkin:
    base-url: ${JAEGER_COLLECTOR_URL}
    service:
      name: edisplitter
    enabled: true 
  sleuth:
    opentracing:
      enabled: true   
    trace-id128: true
    sampler:
      probability: 1.0
    messaging:
      kafka:
        enabled: false
              
server:
  port: 9306
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,env,httptrace,loggers

logging:
  level:
    ROOT: ERROR
    com.atd.microservices.core.edisplitter: DEBUG

apigateway:
  url: '${APIGATEWAY_URL}'
  
edisplitter:
  fusePath: /edi-outbound-files